spring.application.name=five-min-markets
spring.datasource.url=jdbc:mysql://localhost:3306/marketdata
spring.datasource.username=root
spring.datasource.password=Zulutime1*
binance.dl.config.start=2018-01-01
binance.dl.config.end=2026-07-14
binance.dl.config.market-code=BTCUSDT
binance.dl.config.period=FIVE_MINUTES
spring.jpa.hibernate.ddl-auto=update
